package net.konohana.sakuya.maihime.enjurw.constant.code

class ToStaCodeConst {
    companion object {
        // 降車駅名
        const val TOSTA_NAME_BTN01 = "苆谷"
        const val TOSTA_NAME_BTN02 = "東苆谷"
        const val TOSTA_NAME_BTN03 = "茄谷"
        const val TOSTA_NAME_BTN04 = "上茄谷"
        const val TOSTA_NAME_BTN05 = "笥谷"
        const val TOSTA_NAME_BTN06 = "鵩山"
        const val TOSTA_NAME_BTN07 = "上鵩山"
        const val TOSTA_NAME_BTN08 = "筏谷"
        const val TOSTA_NAME_BTN09 = "中筏谷"
        const val TOSTA_NAME_BTN10 = "蛞川"
        const val TOSTA_NAME_BTN11 = "筮谷"
        const val TOSTA_NAME_BTN12 = "中筮谷"
        const val TOSTA_NAME_BTN13 = "上筮谷"
        const val TOSTA_NAME_BTN14 = "筁谷"
        const val TOSTA_NAME_BTN15 = "諾川"
        const val TOSTA_NAME_BTN16 = "筥谷"
        const val TOSTA_NAME_BTN17 = "本筥谷"
        const val TOSTA_NAME_BTN18 = "笒谷"
        const val TOSTA_NAME_BTN19 = "畭谷"
        const val TOSTA_NAME_BTN20 = "上畭谷"
        const val TOSTA_NAME_BTN21 = "箬谷"
        const val TOSTA_NAME_BTN22 = "西箬谷"
        const val TOSTA_NAME_BTN23 = "苕谷"
        const val TOSTA_NAME_BTN24 = "東苕谷"
        const val TOSTA_NAME_BTN25 = "扆谷"
        const val TOSTA_NAME_BTN26 = "奥扆谷"
        const val TOSTA_NAME_BTN27 = "珩谷"
        const val TOSTA_NAME_BTN28 = "中珩谷"
        const val TOSTA_NAME_BTN29 = "上珩谷"
        const val TOSTA_NAME_BTN30 = "玿谷"
        const val TOSTA_NAME_BTN31 = "上玿谷"
        const val TOSTA_NAME_BTN32 = "珮谷"
        const val TOSTA_NAME_BTN33 = "上珮谷"

        // 降車駅コード
        const val TOSTA_CODE_BTN01 = "TORW0101"
        const val TOSTA_CODE_BTN02 = "TORW0102"
        const val TOSTA_CODE_BTN03 = "TORW0201"
        const val TOSTA_CODE_BTN04 = "TORW0202"
        const val TOSTA_CODE_BTN05 = "TORW0301"
        const val TOSTA_CODE_BTN06 = "TORW0302"
        const val TOSTA_CODE_BTN07 = "TORW0303"
        const val TOSTA_CODE_BTN08 = "TORW0401"
        const val TOSTA_CODE_BTN09 = "TORW0402"
        const val TOSTA_CODE_BTN10 = "TORW0403"
        const val TOSTA_CODE_BTN11 = "TORW0501"
        const val TOSTA_CODE_BTN12 = "TORW0502"
        const val TOSTA_CODE_BTN13 = "TORW0503"
        const val TOSTA_CODE_BTN14 = "TORW0601"
        const val TOSTA_CODE_BTN15 = "TORW0602"
        const val TOSTA_CODE_BTN16 = "TORW0701"
        const val TOSTA_CODE_BTN17 = "TORW0702"
        const val TOSTA_CODE_BTN18 = "TORW0801"
        const val TOSTA_CODE_BTN19 = "TORW0802"
        const val TOSTA_CODE_BTN20 = "TORW0803"
        const val TOSTA_CODE_BTN21 = "TORW0901"
        const val TOSTA_CODE_BTN22 = "TORW0902"
        const val TOSTA_CODE_BTN23 = "TORW1001"
        const val TOSTA_CODE_BTN24 = "TORW1002"
        const val TOSTA_CODE_BTN25 = "TORW1101"
        const val TOSTA_CODE_BTN26 = "TORW1102"
        const val TOSTA_CODE_BTN27 = "TORW1201"
        const val TOSTA_CODE_BTN28 = "TORW1202"
        const val TOSTA_CODE_BTN29 = "TORW1203"
        const val TOSTA_CODE_BTN30 = "TORW1301"
        const val TOSTA_CODE_BTN31 = "TORW1302"
        const val TOSTA_CODE_BTN32 = "TORW1401"
        const val TOSTA_CODE_BTN33 = "TORW1402"
    }
}
