package net.konohana.sakuya.maihime.enjurw.constant.code

class ToStaCodeConst {
    companion object {
        // 降車駅名
        const val TOSTA_NAME_BTN01 = "苆谷"
        const val TOSTA_NAME_BTN02 = "東苆谷"
        const val TOSTA_NAME_BTN03 = "茄谷"
        const val TOSTA_NAME_BTN04 = "上茄谷"
        const val TOSTA_NAME_BTN05 = "笥谷"
        const val TOSTA_NAME_BTN06 = "鵩山"
        const val TOSTA_NAME_BTN07 = "上鵩山"
        const val TOSTA_NAME_BTN08 = "筏谷"
        const val TOSTA_NAME_BTN09 = "中筏谷"
        const val TOSTA_NAME_BTN10 = "蛞川"
        const val TOSTA_NAME_BTN11 = "筮谷"
        const val TOSTA_NAME_BTN12 = "中筮谷"
        const val TOSTA_NAME_BTN13 = "上筮谷"
        const val TOSTA_NAME_BTN14 = "筁谷"
        const val TOSTA_NAME_BTN15 = "諾川"
        const val TOSTA_NAME_BTN16 = "筥谷"
        const val TOSTA_NAME_BTN17 = "本筥谷"
        const val TOSTA_NAME_BTN18 = "笒谷"
        const val TOSTA_NAME_BTN19 = "畭谷"
        const val TOSTA_NAME_BTN20 = "上畭谷"
        const val TOSTA_NAME_BTN21 = "箬谷"
        const val TOSTA_NAME_BTN22 = "西箬谷"
        const val TOSTA_NAME_BTN23 = "苕谷"
        const val TOSTA_NAME_BTN24 = "東苕谷"
        const val TOSTA_NAME_BTN25 = "扆谷"
        const val TOSTA_NAME_BTN26 = "奥扆谷"
        const val TOSTA_NAME_BTN27 = "珩谷"
        const val TOSTA_NAME_BTN28 = "中珩谷"
        const val TOSTA_NAME_BTN29 = "上珩谷"
        const val TOSTA_NAME_BTN30 = "玿谷"
        const val TOSTA_NAME_BTN31 = "上玿谷"
        const val TOSTA_NAME_BTN32 = "珮谷"
        const val TOSTA_NAME_BTN33 = "上珮谷"
        const val TOSTA_NAME_BTN34 = "荍谷"
        const val TOSTA_NAME_BTN35 = "上荍谷"

        // 降車駅名(降車駅候補2)
        const val TOSTA_NAME_OP2_BTN01 = "梼谷"
        const val TOSTA_NAME_OP2_BTN02 = "東梼谷"
        const val TOSTA_NAME_OP2_BTN03 = "卯花"
        const val TOSTA_NAME_OP2_BTN04 = "上卯花"
        const val TOSTA_NAME_OP2_BTN05 = "槐谷"
        const val TOSTA_NAME_OP2_BTN07= "槐谷"
        const val TOSTA_NAME_OP2_BTN08 = "苆谷"
        const val TOSTA_NAME_OP2_BTN09 = "拯川"
        const val TOSTA_NAME_OP2_BTN10 = "上拯川"
        const val TOSTA_NAME_OP2_BTN11 = "茄谷"
        const val TOSTA_NAME_OP2_BTN12 = "笥谷"
        const val TOSTA_NAME_OP2_BTN13 = "岩組"
        const val TOSTA_NAME_OP2_BTN14 = "筏谷"
        const val TOSTA_NAME_OP2_BTN15 = "宿田"
        const val TOSTA_NAME_OP2_BTN16 = "瑞堂"
        const val TOSTA_NAME_OP2_BTN17 = "筮谷"
        const val TOSTA_NAME_OP2_BTN18 = "和瀬"
        const val TOSTA_NAME_OP2_BTN19 = "上和瀬"
        const val TOSTA_NAME_OP2_BTN20 = "卯塚"
        const val TOSTA_NAME_OP2_BTN25 = "東卯塚"
        const val TOSTA_NAME_OP2_BTN26 = "筁谷"
        const val TOSTA_NAME_OP2_BTN27 = "筥谷"
        const val TOSTA_NAME_OP2_BTN28 = "粥坂"
        const val TOSTA_NAME_OP2_BTN29 = "笒谷"
        const val TOSTA_NAME_OP2_BTN30 = "箬谷"
        const val TOSTA_NAME_OP2_BTN31 = "梧谷"


        // 降車駅コード
        const val TOSTA_CODE_BTN01 = "TORW0101"
        const val TOSTA_CODE_BTN02 = "TORW0102"
        const val TOSTA_CODE_BTN03 = "TORW0201"
        const val TOSTA_CODE_BTN04 = "TORW0202"
        const val TOSTA_CODE_BTN05 = "TORW0301"
        const val TOSTA_CODE_BTN06 = "TORW0302"
        const val TOSTA_CODE_BTN07 = "TORW0303"
        const val TOSTA_CODE_BTN08 = "TORW0401"
        const val TOSTA_CODE_BTN09 = "TORW0402"
        const val TOSTA_CODE_BTN10 = "TORW0403"
        const val TOSTA_CODE_BTN11 = "TORW0501"
        const val TOSTA_CODE_BTN12 = "TORW0502"
        const val TOSTA_CODE_BTN13 = "TORW0503"
        const val TOSTA_CODE_BTN14 = "TORW0601"
        const val TOSTA_CODE_BTN15 = "TORW0602"
        const val TOSTA_CODE_BTN16 = "TORW0701"
        const val TOSTA_CODE_BTN17 = "TORW0702"
        const val TOSTA_CODE_BTN18 = "TORW0801"
        const val TOSTA_CODE_BTN19 = "TORW0802"
        const val TOSTA_CODE_BTN20 = "TORW0803"
        const val TOSTA_CODE_BTN21 = "TORW0901"
        const val TOSTA_CODE_BTN22 = "TORW0902"
        const val TOSTA_CODE_BTN23 = "TORW1001"
        const val TOSTA_CODE_BTN24 = "TORW1002"
        const val TOSTA_CODE_BTN25 = "TORW1101"
        const val TOSTA_CODE_BTN26 = "TORW1102"
        const val TOSTA_CODE_BTN27 = "TORW1201"
        const val TOSTA_CODE_BTN28 = "TORW1202"
        const val TOSTA_CODE_BTN29 = "TORW1203"
        const val TOSTA_CODE_BTN30 = "TORW1301"
        const val TOSTA_CODE_BTN31 = "TORW1302"
        const val TOSTA_CODE_BTN32 = "TORW1401"
        const val TOSTA_CODE_BTN33 = "TORW1402"
        const val TOSTA_CODE_BTN34 = "TORW1501"
        const val TOSTA_CODE_BTN35 = "TORW1502"

        // 降車駅コード(降車駅候補2)
        const val TOSTA_CODE_OP2_BTN01 = "TORW1601"
        const val TOSTA_CODE_OP2_BTN02 = "TORW1602"
        const val TOSTA_CODE_OP2_BTN03 = "TORW1603"
        const val TOSTA_CODE_OP2_BTN04 = "TORW1604"
        const val TOSTA_CODE_OP2_BTN05 = "TORW1605"
        const val TOSTA_CODE_OP2_BTN07 = "TORW1701"
        const val TOSTA_CODE_OP2_BTN08 = "TORW1702"
        const val TOSTA_CODE_OP2_BTN09 = "TORW1703"
        const val TOSTA_CODE_OP2_BTN10 = "TORW1704"
        const val TOSTA_CODE_OP2_BTN11 = "TORW1705"
        const val TOSTA_CODE_OP2_BTN12 = "TORW1706"
        const val TOSTA_CODE_OP2_BTN13 = "TORW1707"
        const val TOSTA_CODE_OP2_BTN14 = "TORW1708"
        const val TOSTA_CODE_OP2_BTN15 = "TORW1709"
        const val TOSTA_CODE_OP2_BTN16 = "TORW1710"
        const val TOSTA_CODE_OP2_BTN17 = "TORW1711"
        const val TOSTA_CODE_OP2_BTN18 = "TORW1712"
        const val TOSTA_CODE_OP2_BTN19 = "TORW1713"
        const val TOSTA_CODE_OP2_BTN20 = "TORW1714"
        const val TOSTA_CODE_OP2_BTN25 = "TORW1802"
        const val TOSTA_CODE_OP2_BTN26 = "TORW1803"
        const val TOSTA_CODE_OP2_BTN27 = "TORW1804"
        const val TOSTA_CODE_OP2_BTN28 = "TORW1805"
        const val TOSTA_CODE_OP2_BTN29 = "TORW1806"
        const val TOSTA_CODE_OP2_BTN30 = "TORW1807"
        const val TOSTA_CODE_OP2_BTN31 = "TORW1808"
    }
}
