package net.konohana.sakuya.maihime.enjurw.constant.api

class InquiryApiUrlConst {
    companion object {
        const val INQUIRY_API_ENJURW01_FROMSTA = "http://localhost:8080/api/fromsta/enjurw01/"
        const val INQUIRY_API_ENJURW02_FROMSTA = "http://localhost:8080/api/fromsta/enjurw02/"
        const val INQUIRY_API_ENJURW03_FROMSTA = "http://localhost:8080/api/fromsta/enjurw03/"
        const val INQUIRY_API_ENJURW04_FROMSTA = "http://localhost:8080/api/fromsta/enjurw04/"
        const val INQUIRY_API_ENJURW05_FROMSTA = "http://localhost:8080/api/fromsta/enjurw05/"
        const val INQUIRY_API_ENJURW06_FROMSTA = "http://localhost:8080/api/fromsta/enjurw06/"
        const val INQUIRY_API_ENJURW07_FROMSTA = "http://localhost:8080/api/fromsta/enjurw07/"
        const val INQUIRY_API_ENJURW08_FROMSTA = "http://localhost:8080/api/fromsta/enjurw08/"
        const val INQUIRY_API_ENJURW09_FROMSTA = "http://localhost:8080/api/fromsta/enjurw09/"
        const val INQUIRY_API_ENJURW10_FROMSTA = "http://localhost:8080/api/fromsta/enjurw10/"
        const val INQUIRY_API_ENJURW11_FROMSTA = "http://localhost:8080/api/fromsta/enjurw11/"
        const val INQUIRY_API_ENJURW12_FROMSTA = "http://localhost:8080/api/fromsta/enjurw12/"
        const val INQUIRY_API_ENJURW13_FROMSTA = "http://localhost:8080/api/fromsta/enjurw13/"
        const val INQUIRY_API_ENJURW14_FROMSTA = "http://localhost:8080/api/fromsta/enjurw14/"
        const val INQUIRY_API_ENJURW15_FROMSTA = "http://localhost:8080/api/fromsta/enjurw15/"
        const val INQUIRY_API_ENJURW16_FROMSTA = "http://localhost:8080/api/fromsta/enjurw16/"
        const val INQUIRY_API_ENJURW17_FROMSTA = "http://localhost:8080/api/fromsta/enjurw17/"
        const val INQUIRY_API_ENJURW18_FROMSTA = "http://localhost:8080/api/fromsta/enjurw18/"
        const val INQUIRY_API_ENJURW19_FROMSTA = "http://localhost:8080/api/fromsta/enjurw19/"
        const val INQUIRY_API_NOTFOUND_FROMSTA = "http://localhost:8080/api/fromsta/notfound/"
        const val INQUIRY_API_ENJURW01_TOSTA = "http://localhost:8080/api/tosta/enjurw01/"
        const val INQUIRY_API_ENJURW02_TOSTA = "http://localhost:8080/api/tosta/enjurw02/"
        const val INQUIRY_API_ENJURW03_TOSTA = "http://localhost:8080/api/tosta/enjurw03/"
        const val INQUIRY_API_ENJURW04_TOSTA = "http://localhost:8080/api/tosta/enjurw04/"
        const val INQUIRY_API_ENJURW05_TOSTA = "http://localhost:8080/api/tosta/enjurw05/"
        const val INQUIRY_API_ENJURW06_TOSTA = "http://localhost:8080/api/tosta/enjurw06/"
        const val INQUIRY_API_ENJURW07_TOSTA = "http://localhost:8080/api/tosta/enjurw07/"
        const val INQUIRY_API_ENJURW08_TOSTA = "http://localhost:8080/api/tosta/enjurw08/"
        const val INQUIRY_API_ENJURW09_TOSTA = "http://localhost:8080/api/tosta/enjurw09/"
        const val INQUIRY_API_ENJURW10_TOSTA = "http://localhost:8080/api/tosta/enjurw10/"
        const val INQUIRY_API_ENJURW11_TOSTA = "http://localhost:8080/api/tosta/enjurw11/"
        const val INQUIRY_API_ENJURW12_TOSTA = "http://localhost:8080/api/tosta/enjurw12/"
        const val INQUIRY_API_ENJURW13_TOSTA = "http://localhost:8080/api/tosta/enjurw13/"
        const val INQUIRY_API_ENJURW14_TOSTA = "http://localhost:8080/api/tosta/enjurw14/"
        const val INQUIRY_API_ENJURW15_TOSTA = "http://localhost:8080/api/tosta/enjurw15/"
        const val INQUIRY_API_ENJURW16_TOSTA = "http://localhost:8080/api/tosta/enjurw16/"
        const val INQUIRY_API_ENJURW17_TOSTA = "http://localhost:8080/api/tosta/enjurw17/"
        const val INQUIRY_API_ENJURW18_TOSTA = "http://localhost:8080/api/tosta/enjurw18/"
        const val INQUIRY_API_ENJURW19_TOSTA = "http://localhost:8080/api/tosta/enjurw19/"
        const val INQUIRY_API_NOTFOUND_TOSTA = "http://localhost:8080/api/tosta/notfound/"
    }
}
