package net.konohana.sakuya.maihime.enjurw.constant.title

class WebViewTitleConst {
    companion object {
        const val WEBVIEW_TITLE_ENJURW01_FROMSTA = "乗車駅照会: えんじゅ交通苆谷線"
        const val WEBVIEW_TITLE_ENJURW02_FROMSTA = "乗車駅照会: えんじゅ交通茄谷線"
        const val WEBVIEW_TITLE_ENJURW03_FROMSTA = "乗車駅照会: えんじゅ交通笥谷線"
        const val WEBVIEW_TITLE_ENJURW04_FROMSTA = "乗車駅照会: えんじゅ交通筏谷線"
        const val WEBVIEW_TITLE_ENJURW05_FROMSTA = "乗車駅照会: えんじゅ交通筮谷線"
        const val WEBVIEW_TITLE_ENJURW06_FROMSTA = "乗車駅照会: えんじゅ交通筁谷線"
        const val WEBVIEW_TITLE_ENJURW07_FROMSTA = "乗車駅照会: えんじゅ交通筥谷線"
        const val WEBVIEW_TITLE_ENJURW08_FROMSTA = "乗車駅照会: えんじゅ交通笒谷線"
        const val WEBVIEW_TITLE_ENJURW09_FROMSTA = "乗車駅照会: えんじゅ交通箬谷線"
        const val WEBVIEW_TITLE_ENJURW10_FROMSTA = "乗車駅照会: えんじゅ交通苕谷線"
        const val WEBVIEW_TITLE_ENJURW11_FROMSTA = "乗車駅照会: えんじゅ交通扆谷線"
        const val WEBVIEW_TITLE_ENJURW12_FROMSTA = "乗車駅照会: えんじゅ交通珩谷線"
        const val WEBVIEW_TITLE_ENJURW13_FROMSTA = "乗車駅照会: えんじゅ交通玿谷線"
        const val WEBVIEW_TITLE_ENJURW14_FROMSTA = "乗車駅照会: えんじゅ交通珮谷線"
        const val WEBVIEW_TITLE_ENJURW15_FROMSTA = "乗車駅照会: えんじゅ交通荍谷線"
        const val WEBVIEW_TITLE_ENJURW16_FROMSTA = "乗車駅照会: えんじゅ交通槐谷線"
        const val WEBVIEW_TITLE_ENJURW17_FROMSTA = "乗車駅照会: えんじゅ交通拯川線"
        const val WEBVIEW_TITLE_ENJURW18_FROMSTA = "乗車駅照会: えんじゅ交通卯塚線"
        const val WEBVIEW_TITLE_ENJURW19_FROMSTA = "乗車駅照会: えんじゅ交通瑞堂線"
        const val WEBVIEW_TITLE_ENJURW01_TOSTA = "降車駅照会: えんじゅ交通苆谷線"
        const val WEBVIEW_TITLE_ENJURW02_TOSTA = "降車駅照会: えんじゅ交通茄谷線"
        const val WEBVIEW_TITLE_ENJURW03_TOSTA = "降車駅照会: えんじゅ交通笥谷線"
        const val WEBVIEW_TITLE_ENJURW04_TOSTA = "降車駅照会: えんじゅ交通筏谷線"
        const val WEBVIEW_TITLE_ENJURW05_TOSTA = "降車駅照会: えんじゅ交通筮谷線"
        const val WEBVIEW_TITLE_ENJURW06_TOSTA = "降車駅照会: えんじゅ交通筁谷線"
        const val WEBVIEW_TITLE_ENJURW07_TOSTA = "降車駅照会: えんじゅ交通筥谷線"
        const val WEBVIEW_TITLE_ENJURW08_TOSTA = "降車駅照会: えんじゅ交通笒谷線"
        const val WEBVIEW_TITLE_ENJURW09_TOSTA = "降車駅照会: えんじゅ交通箬谷線"
        const val WEBVIEW_TITLE_ENJURW10_TOSTA = "降車駅照会: えんじゅ交通苕谷線"
        const val WEBVIEW_TITLE_ENJURW11_TOSTA = "降車駅照会: えんじゅ交通扆谷線"
        const val WEBVIEW_TITLE_ENJURW12_TOSTA = "降車駅照会: えんじゅ交通珩谷線"
        const val WEBVIEW_TITLE_ENJURW13_TOSTA = "降車駅照会: えんじゅ交通玿谷線"
        const val WEBVIEW_TITLE_ENJURW14_TOSTA = "降車駅照会: えんじゅ交通珮谷線"
        const val WEBVIEW_TITLE_ENJURW15_TOSTA = "降車駅照会: えんじゅ交通荍谷線"
        const val WEBVIEW_TITLE_ENJURW16_TOSTA = "降車駅照会: えんじゅ交通槐谷線"
        const val WEBVIEW_TITLE_ENJURW17_TOSTA = "降車駅照会: えんじゅ交通拯川線"
        const val WEBVIEW_TITLE_ENJURW18_TOSTA = "降車駅照会: えんじゅ交通卯塚線"
        const val WEBVIEW_TITLE_ENJURW19_TOSTA = "降車駅照会: えんじゅ交通瑞堂線"
    }
}
