package net.konohana.sakuya.maihime.enjurw.constant.webview

class WebViewUrlConst {
    companion object {
        const val WEBVIEW_URL_ENJURW01 = "http://localhost:8080/enjurw01"
        const val WEBVIEW_URL_ENJURW02 = "http://localhost:8080/enjurw02"
        const val WEBVIEW_URL_ENJURW03 = "http://localhost:8080/enjurw03"
        const val WEBVIEW_URL_ENJURW04 = "http://localhost:8080/enjurw04"
        const val WEBVIEW_URL_ENJURW05 = "http://localhost:8080/enjurw05"
        const val WEBVIEW_URL_ENJURW06 = "http://localhost:8080/enjurw06"
        const val WEBVIEW_URL_ENJURW07 = "http://localhost:8080/enjurw07"
        const val WEBVIEW_URL_ENJURW08 = "http://localhost:8080/enjurw08"
        const val WEBVIEW_URL_ENJURW09 = "http://localhost:8080/enjurw09"
        const val WEBVIEW_URL_ENJURW10 = "http://localhost:8080/enjurw10"
        const val WEBVIEW_URL_ENJURW11 = "http://localhost:8080/enjurw11"
        const val WEBVIEW_URL_ENJURW12 = "http://localhost:8080/enjurw12"
        const val WEBVIEW_URL_ENJURW13 = "http://localhost:8080/enjurw13"
        const val WEBVIEW_URL_ENJURW14 = "http://localhost:8080/enjurw14"
        const val WEBVIEW_URL_ENJURW15 = "http://localhost:8080/enjurw15"
        const val WEBVIEW_URL_ENJURW16 = "http://localhost:8080/enjurw16"
        const val WEBVIEW_URL_ENJURW17 = "http://localhost:8080/enjurw17"
        const val WEBVIEW_URL_ENJURW18 = "http://localhost:8080/enjurw18"
        const val WEBVIEW_URL_ENJURW19 = "http://localhost:8080/enjurw19"
        const val WEBVIEW_URL_TOSTA_ENJURW01 = "http://localhost:8080/tostainfo/enjurw01"
        const val WEBVIEW_URL_TOSTA_ENJURW02 = "http://localhost:8080/tostainfo/enjurw02"
        const val WEBVIEW_URL_TOSTA_ENJURW03 = "http://localhost:8080/tostainfo/enjurw03"
        const val WEBVIEW_URL_TOSTA_ENJURW04 = "http://localhost:8080/tostainfo/enjurw04"
        const val WEBVIEW_URL_TOSTA_ENJURW05 = "http://localhost:8080/tostainfo/enjurw05"
        const val WEBVIEW_URL_TOSTA_ENJURW06 = "http://localhost:8080/tostainfo/enjurw06"
        const val WEBVIEW_URL_TOSTA_ENJURW07 = "http://localhost:8080/tostainfo/enjurw07"
        const val WEBVIEW_URL_TOSTA_ENJURW08 = "http://localhost:8080/tostainfo/enjurw08"
        const val WEBVIEW_URL_TOSTA_ENJURW09 = "http://localhost:8080/tostainfo/enjurw09"
        const val WEBVIEW_URL_TOSTA_ENJURW10 = "http://localhost:8080/tostainfo/enjurw10"
        const val WEBVIEW_URL_TOSTA_ENJURW11 = "http://localhost:8080/tostainfo/enjurw11"
        const val WEBVIEW_URL_TOSTA_ENJURW12 = "http://localhost:8080/tostainfo/enjurw12"
        const val WEBVIEW_URL_TOSTA_ENJURW13 = "http://localhost:8080/tostainfo/enjurw13"
        const val WEBVIEW_URL_TOSTA_ENJURW14 = "http://localhost:8080/tostainfo/enjurw14"
        const val WEBVIEW_URL_TOSTA_ENJURW15 = "http://localhost:8080/tostainfo/enjurw15"
        const val WEBVIEW_URL_TOSTA_ENJURW16 = "http://localhost:8080/tostainfo/enjurw16"
        const val WEBVIEW_URL_TOSTA_ENJURW17 = "http://localhost:8080/tostainfo/enjurw17"
        const val WEBVIEW_URL_TOSTA_ENJURW18 = "http://localhost:8080/tostainfo/enjurw18"
        const val WEBVIEW_URL_TOSTA_ENJURW19 = "http://localhost:8080/tostainfo/enjurw19"
    }
}
